config/routes.rb
Rails.application.routes.draw do
  # get 'room_memberships/create'
  # get 'room_memberships/destroy'
  # root "static_pages#index"
  root "rooms#index"
  get 'static_pages/about'
  get 'static_pages/help'
  devise_for :users
  resources :rooms, only: [:show, :index, :create, :new, :destroy, :edit] do
    resource :room_memberships, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # setting for letter_opener_web gem
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :room_ownership, dependent: :destroy
  has_many :words, dependent: :destroy
  has_many :room_memberships, dependent: :destroy
end

app/models/room_membership.rb
class RoomMembership < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room_ownership.rb
class RoomOwnership < ApplicationRecord
  belongs_to :user
  has_one :room, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :words, dependent: :nullify
  has_many :room_ownerships, dependent: :destroy
  has_many :rooms, through: :room_ownerships
  has_many :room_memberships, dependent: :destroy

  after_create_commit { GetEveryonesMembershipJob.perform_later self }
end

app/models/word.rb
class Word < ApplicationRecord
  validates :content, presence: true
  after_create_commit { WordBroadcastJob.perform_later self }
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def have_ownership?(room)
    room.room_ownership.user == current_user
  end

  def have_membership?(room)
    if room.room_memberships.find_by(user_id: current_user.id)
      true
    else
      false
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:email, :name, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

end

app/controllers/room_memberships_controller.rb
class RoomMembershipsController < ApplicationController
  before_action :set_room

  def create
    set_user
    unless have_ownership?(@room)
      redirect_to rooms_path, alert: "権限がないためその操作を完了できません"
      return
    end
    unless @user
      redirect_to edit_room_path(@room.id), alert: "ユーザーが見つかりませんでした"
      return
    end
    @room_membership = @room.room_memberships.build
    @room_membership.user = @user
    if @room_membership.save
      redirect_to edit_room_path(@room.id), notice: "ユーザーを追加しました"
    else
      redirect_to edit_room_path(@room.id), alert: "ユーザーを追加できませんでした"
    end
  end

  def destroy
    set_room_membership
    unless have_ownership?(@room)
      redirect_to rooms_path, alert: "権限がないためその操作を完了できません"
      return
    end
    if @room_membership.destroy
      redirect_to edit_room_path(@room.id), notice: "ユーザーを退出させました"
    else
      redirect_to edit_room_path(@room.id), alert: "ユーザーを退出させることができませんでした"
    end
  end

  private

  def set_user
    @user = User.find_by(name: params[:user_name])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_room_membership
    @room_membership = RoomMembership.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show update edit delete destroy]

  def index
  end

  def show
    unless have_membership?(@room)
      redirect_to rooms_path, alert: "権限がないためその操作を完了できません"
      return
    end
    @words = @room.words
  end

  def new
    @room = Room.new
  end

  def create
    @room_ownership = current_user.room_ownerships.build
    @room = @room_ownership.build_room(room_params)
    @room_membership = @room.room_memberships.build
    @room_membership.user = current_user
    if @room_ownership.save && @room.save && @room_membership.save
      redirect_to rooms_path
    else
      render "new"
    end
  end

  def destroy
    unless have_ownership?(@room)
      redirect_to rooms_path, alert: "権限がないためその操作を完了できません"
      return
    end

    if @room.destroy
      redirect_to rooms_path, notice: "削除しました"
    else
      redirect_to rooms_path, alert: "削除に失敗しました"
    end
  end

  def edit
    unless have_ownership?(@room)
      redirect_to rooms_path, alert: "権限がないためその操作を完了できません"
      return
    end
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_memberships_helper.rb
module RoomMembershipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_alert.html.erb
<div class="row">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_head.html.erb
<title>しりとり</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width,initial-scale=1">

<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<div class="row">
  <ul>
    <li><%= link_to "トップ", root_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "部屋リスト", rooms_path %></li>
      <li><%= link_to "部屋を作る", new_room_path %></li>
      <li><%= link_to "ユーザー情報を編集", edit_user_registration_path %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "サインアップ", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>

  <body>
    <div class="container"
    <% if content_for?(:body_attributes) %>
      <%= yield(:body_attributes) %>
    <% end %>
    >
      <%= render "layouts/alert" %>
      <%= render "layouts/header" %>
      <% if user_signed_in? %>
        <div class="row">
          <strong>ユーザー情報</strong>
          <ul>
            <li id="user_id" data-user_id="<%= current_user.id %>">ID: <%= current_user.id %></li>
            <li>ユーザー名: <%= current_user.name %></li>
            <li>メールアドレス: <%= current_user.email %></li>
          </ul>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/edit.html.erb
<div>
  <h3><%= @room.name %></h3>
  <%= form_with url: room_room_memberships_path(@room.id) do |f| %>
    <div class="field">
      <%= f.label :user_name, "ユーザー名" %>
      <%= f.text_field :user_name, autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "追加" %>
    </div>
  <% end %>
  <ul>
    <% @room.room_memberships.each do |room_membership| %>
      <li><%= room_membership.user.name %> <%= link_to "退出", room_room_memberships_path(@room.id, id: room_membership.id), method: :delete %></li>
    <% end %>
  </ul>
</div>

app/views/rooms/index.html.erb
<div>
  <h3>管理している部屋</h3>
  <ul>
    <% current_user.rooms.each do |room| %>
    <li><%= link_to room.name, room_path(room), data: { turbolinks: false } %> <%= link_to "削除", room_path(room), method: :delete %>　<%= link_to "メンバーの編集", edit_room_path(room) %></li>
    <% end %>
  </ul>
  <h3>入室可能な部屋</h3>
  <ul>
    <% current_user.room_memberships.each do |room_membership| %>
      <li><%= link_to room_membership.room.name, room_path(room_membership.room), data: { turbolinks: false } %></li>
    <% end %>
  </ul>
</div>

app/views/rooms/new.html.erb
<%= form_with model: @room do |f| %>

  <div class="field">
    <%= f.label :name, "name" %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "create" %>
  </div>

<% end %>

app/views/rooms/show.html.erb
<% content_for(:body_attributes) do %>
    data-turbolinks="false"
<% end %>
<%= javascript_pack_tag 'channels', 'data-turbolinks-track': 'reload' %>
<h1><%= @room.name %></h1>
<div id="words" data-room_id="<%= @room.id %>">
  <%= render @words %>
</div>

<%= label_tag :content, "しゃべる" %>
<%= text_field_tag :content, nil, data: { behavior: "room_speaker" } %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/words/_word.html.erb
<div class="word">
  <p>
  <%= word.user.name %>:
  <%= word.content %>
  </p>
</div>